# Generated by Django 6.0.3 on 2026-03-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='Дата начала заморозки')),
                ('to_date', models.DateField(verbose_name='Дата окончания заморозки')),
            ],
            options={
                'verbose_name': 'Заморозка',
                'verbose_name_plural': 'Заморозки',
                'db_table': 'membership_freeze',
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('scope', models.CharField(choices=[('club', 'Один клуб'), ('network', 'Вся сеть')], max_length=10, verbose_name='Охват')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration_months', models.PositiveIntegerField(verbose_name='Длительность (мес.)')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'db_table': 'membership_plan',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('frozen', 'Заморожен'), ('expired', 'Истёк'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Статус')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='clubs.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'db_table': 'membership',
                'ordering': ['-start_date'],
            },
        ),
    ]
