# Generated by Django 6.0.3 on 2026-03-14 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('timezone', models.CharField(max_length=50, verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
                'db_table': 'club',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('kind', models.CharField(choices=[('gym', 'Тренажёрный зал'), ('pool', 'Бассейн'), ('spa', 'SPA'), ('studio', 'Студия')], max_length=50, verbose_name='Тип')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='clubs.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
                'db_table': 'room',
                'ordering': ['club', 'name'],
            },
        ),
    ]
