# Generated by Django 6.0.3 on 2026-03-14 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('default_duration', models.PositiveIntegerField(help_text='Длительность в минутах', verbose_name='Длительность (мин.)')),
            ],
            options={
                'verbose_name': 'Тип тренировки',
                'verbose_name_plural': 'Типы тренировок',
                'db_table': 'workout_type',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PersonalTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ts', models.DateTimeField(verbose_name='Начало')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Длительность (мин.)')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'trainer'}, on_delete=django.db.models.deletion.CASCADE, related_name='pt_as_trainer', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Персональная тренировка',
                'verbose_name_plural': 'Персональные тренировки',
                'db_table': 'personal_training',
                'ordering': ['-start_ts'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ts', models.DateTimeField(verbose_name='Начало')),
                ('end_ts', models.DateTimeField(verbose_name='Конец')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('ongoing', 'Идёт'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='clubs.club', verbose_name='Клуб')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='clubs.room', verbose_name='Зал')),
                ('trainer', models.ForeignKey(blank=True, limit_choices_to={'role': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
                ('workout_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='workouts.workouttype', verbose_name='Тип тренировки')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'db_table': 'workout_session',
                'ordering': ['-start_ts'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждена'), ('cancelled', 'Отменена'), ('attended', 'Посещена')], default='confirmed', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='workouts.workoutsession', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'db_table': 'booking',
                'ordering': ['-created_at'],
                'unique_together': {('session', 'user')},
            },
        ),
    ]
